### ISSUE TITLE
热更新调试

### ISSUE THREAD

**Issue by VinlorJiang** [DemoJ/ThinNav#4]
请问前端代码怎么边修改边在浏览器上看到效果？而不用通过打包、部署到后端，再去获取数据，谢谢

**Comment by DemoJ** [comment]
在用户端项目中，我使用了 npm 进行开发调试，运行 npm run serve 就能启动项目，并且支持热更新，代码修改后会自动刷新页面。

后台管理系统则采用了 pnpm，这是原作者推荐的包管理工具。你可以使用 pnpm dev 启动项目，同样具备热更新功能。

**Comment by VinlorJiang** [comment]
明白，非常感谢！但是就目前前端navigation这个项目，页面内容较少，导航的数据是从后端获取的，我在执行npm run serve时报错Proxy error: Could not proxy request /websites/?all_data=true from localhost:8081 to http://127.0.0.1:8000，请问大佬这个怎么解决？非常感谢

**Comment by DemoJ** [comment]
你这是后端服务没有启动吧，需要先去Python项目目录下，安装依赖后再运行main.py

**Comment by DemoJ** [comment]
如果要本地调试，推荐还是代码拉下来全部本地启动。docker这一套适合线上部署一把梭。
