### ISSUE TITLE
JWT密钥硬编码存在未授权访问

### ISSUE THREAD

**Issue by cnzzr** [DemoJ/ThinNav#6]
auth.py中硬编码了JWT的密钥，而认证逻辑为取play中的用户名，因此存在直接登录admin的安全问题

![image](https://github.com/user-attachments/assets/04e9dcb9-ac55-49e8-9e46-d789f3ed1d65)

**Comment by DemoJ** [comment]
感谢提醒。。稍后我改成从环境变量获取吧

**Comment by DemoJ** [comment]
你不提醒，我都没反应过来，第一反应是这不后端嘛，别人获取不到密钥。再一想，我都开源了，那人人都知道密钥
